### ISSUE TITLE
"Analyze Current Vue File" doesn't working. Infinite loading

### ISSUE THREAD

**Issue by NinoZombie** [Flamenco/intellivue#5] opened 2019-10-15 05:59 UTC
# Baseline
Ubuntu 18.04 with x11
Fresh installation of PHPStorm 2019.2.1 (with bundled Vue.js and JavaScript plugins)
Fresh generated Vue project with SFCs
`sudo apt install openjdk-8-jdk openjfx` is executed

# Problem
After i select `App.vue` file and click on `Vue` --> `Analyze Current Vue File` 
a window appears with "Loading IntelliVue and Analyzing..." text. 
And... nothing changes after that.

**Comment by Flamenco** [comment] 2019-10-15 12:08
Thanks for the report @NinoZombie.

Can you please check the IJ PHPStorm log and comment if there are any relevant entries.

Also
1.  Has this worked for you on previous versions?
2.  Do the other plugin features work?
3.  Are you are using the IJ Java 11 build?

My guess is that it is related to JavaFX and Java  >= 11.

**Comment by NinoZombie** [comment] 2019-10-18 10:34
<details>
  <summary>Piece of log</summary>
  
That things happened immediatly after start `Analyze Current Vue File` . So no one of this lines don't tell us anything interesting about our problem
  
  ```javascript
 2019-10-18 17:50:30,837 [198801363]   WARN - llij.ide.plugins.PluginManager - DeepBugsPython not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,837 [198801363]   WARN - llij.ide.plugins.PluginManager - DeepBugsJavaScript not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,838 [198801364]   WARN - llij.ide.plugins.PluginManager - Gitee not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,838 [198801364]   WARN - llij.ide.plugins.PluginManager - Subversion not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,841 [198801367]   WARN - llij.ide.plugins.PluginManager - Task Management not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,842 [198801368]   WARN - llij.ide.plugins.PluginManager - Command Line Tool Support not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,842 [198801368]   WARN - llij.ide.plugins.PluginManager - Docker not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,843 [198801369]   WARN - llij.ide.plugins.PluginManager - Codeseek developer friendly search not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,843 [198801369]   WARN - llij.ide.plugins.PluginManager - Settings Repository not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,844 [198801370]   WARN - llij.ide.plugins.PluginManager - Prettier not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,844 [198801370]   WARN - llij.ide.plugins.PluginManager - Angular and AngularJS not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,844 [198801370]   WARN - llij.ide.plugins.PluginManager - Shopware not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,844 [198801370]   WARN - llij.ide.plugins.PluginManager - Blade not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,845 [198801371]   WARN - llij.ide.plugins.PluginManager - Go Template not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,846 [198801372]   WARN - llij.ide.plugins.PluginManager - NodeJS not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,846 [198801372]   WARN - llij.ide.plugins.PluginManager - File Watchers not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,847 [198801373]   WARN - llij.ide.plugins.PluginManager - Apache Camel IDEA Plugin not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,847 [198801373]   WARN - llij.ide.plugins.PluginManager - TestCafe runner for Webstorm not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,847 [198801373]   WARN - llij.ide.plugins.PluginManager - Hunspell not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,847 [198801373]   WARN - llij.ide.plugins.PluginManager - Code Notes not loaded: since build 192.6603.28 > PS-192.6262.66 
2019-10-18 17:50:30,847 [198801373]   WARN - llij.ide.plugins.PluginManager - Kubernetes not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:30,848 [198801374]   WARN - llij.ide.plugins.PluginManager - Performance Testing not loaded: since build 192.6603 > PS-192.6262.66 
2019-10-18 17:50:30,848 [198801374]   WARN - llij.ide.plugins.PluginManager - Packages for Apex not loaded: since build 192.6817 > PS-192.6262.66 
2019-10-18 17:50:32,866 [198803392]   INFO - ageJson.NpmRegistryServiceImpl - Found 51 packages (4 with '@web-types' prefix) in 4311ms (https://registry.npmjs.org/-/v1/search?&text=%22%40web-types%22&from=0&size=51) 
2019-10-18 17:50:33,528 [198804054]   INFO - ageJson.NpmRegistryServiceImpl - Found 47 packages (1 with '@web-types' prefix) in 661ms (https://registry.npmjs.org/-/v1/search?&text=%22%40web-types%22&from=51&size=47) 
2019-10-18 17:50:34,599 [198805125]   INFO - ageJson.NpmRegistryServiceImpl - Found 26 packages (0 with '@web-types' prefix) in 1070ms (https://registry.npmjs.org/-/v1/search?&text=%22%40web-types%22&from=98&size=46) 
2019-10-18 17:50:35,072 [198805598]   INFO - ageJson.NpmRegistryServiceImpl - Found 1 dist-tags, 44 versions for @web-types/quasar-framework in 471ms 
2019-10-18 17:50:35,174 [198805700]   INFO - ageJson.NpmRegistryServiceImpl - Found 1 dist-tags, 115 versions for @web-types/vuetify in 573ms 
2019-10-18 17:50:35,345 [198805871]   INFO - ageJson.NpmRegistryServiceImpl - Found 1 dist-tags, 8 versions for @web-types/quasar in 272ms 
2019-10-18 17:50:35,471 [198805997]   INFO - ageJson.NpmRegistryServiceImpl - Found 1 dist-tags, 14 versions for @web-types/vue in 296ms 
2019-10-18 17:50:35,682 [198806208]   INFO - ageJson.NpmRegistryServiceImpl - Found 1 dist-tags, 30 versions for @web-types/bootstrap-vue in 337ms 
  ```

And another one
```javascript
2019-10-18 18:52:18,820 [  62356]   WARN - ution.process.OSProcessHandler - Process has been already terminated: setsid /usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false -c diff.renames=false log --no-walk=unsorted --stdin --pretty=format:%x01%x01%H%x02%x02%P%x02%x02%ct%x02%x02%cn%x02%x02%ce%x02%x02%an%x02%x02%at%x02%x02%ae%x02%x02%s%x02%x02%b%x02%x02%B%x03%x03 --encoding=UTF-8 --name-status -- 
```
</details>

1.  No, this version of PHPStorm is first version I am installed the plugin on 
2.  Yes, other features work.
3.  I don't know. How can i check this?

```bash
$ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

**Comment by Flamenco** [comment] 2019-10-18 14:08
`openjdk version "13.0.1" 2019-10-15`

It seems you have installed Java 13 on your system; IntelliJ has an embedded Java version that is used by default, but can be overridden.  JetBrains provides a Java 8 and Java 11 build.

The `about splash screen` shows the version IJ is actually using.
<img width="719" alt="Screen Shot 2019-10-18 at 9 59 47 AM" src="https://user-images.githubusercontent.com/819940/67100744-38aca780-f18e-11e9-9f0f-8e418f93c3bd.png">

It is also possible your `.vue` file is causing the freeze.  If you see the IntelliVue loading screen, your JavaFX is most likely working, but perhaps there is an API call that is causing the issue.
If your selected `.vue` file is unusual, can you post a minimal example, that when selected and invoked with the analyze command, causes the issue.

I will add some code to try and trap this and report the issue in the next plugin release.

**Comment by Flamenco** [comment] 2019-10-19 13:53
We updated the plugin to `rc.16`.  It has a registration ID in the settings dialog which you can provide to us. We can your your ID to investigate stack traces for your issue.  We also added some additional logging.  Please advise after you install the latest.

**Comment by NinoZombie** [comment] 2019-10-22 01:33
I have this version in accordance with 'About' screen

![image](https://user-images.githubusercontent.com/11488489/67254111-e03b1a00-f4ad-11e9-9d32-c009c26e4266.png)

---
After update plugin to `rc.16` . the problem is not gone.

The `.vue` file is very common (generated by vue-cli)

My ID `Your IntelliVue registration code is 876d40e3-1206-4134-b093-41501bfd888c`

**Comment by Flamenco** [comment] 2019-10-22 09:21
Not too much changed in rc16, so I did not expect it to work.  However, your installation is successfully sending the test exceptions you invoked, so that narrows down the issue.

In our next release we will add more detailed logging that targets your installation so we can find exactly where this is failing.  We will also be able to see if other users that share your platform/product have the same issue.

**Comment by Flamenco** [comment] 2019-10-22 12:44
@NinoZombie 

I reproduced your issue by doing the following:

1. Install Ubuntu Desktop 18.04.3
2. Install PHP Storm (trial version)
3. Create a vue-cli project
4. Install IntelliVue plugin
5. Open app.vue
6. Select 'analyze vue file'

We will try to have this fixed today.  Thanks for your input and patience.

**Comment by Flamenco** [comment] 2019-10-22 14:36
Fixed.  This is resolved in rc.17.  Should make its way into IJ update stream within 2 days.

**Closed as completed by Flamenco** 2019-10-22 14:36 UTC
Labels: bug, confirmed

**Comment by Flamenco** [comment] 2019-10-22 17:18
Looks like this was approved. Please confirm the update works. 

https://plugins.jetbrains.com/plugin/12014-intellivue/update/70972

**Comment by NinoZombie** [comment] 2019-10-23 11:44
Works, thank you :)
